project:
  type: website

website: 
  site-url: "https://benekenobi.github.io/bachelor-kolloquium/"

format:
  html:
    theme: default
    toc: true

resources:
  - "fonts/*.ttf"
  - "*.png"

open-graph: true
twitter-card: true
