---
title: "Kompetenz-Check Auswertung"
---

## Überblick
```{python}
import pandas as pd
import plotly.io as pio
import plotly.express as px
import plotly.graph_objects as go

CUD_COLORS = (
    "#e69f00",  # orange
    "#56b4e9",  # sky-blue
    "#009e73",  # bluish-green
    "#f0e442",  # yellow
    "#0072b2",  # blue
    "#d55e00",  # vermilion
    "#cc79a7",  # reddish-purple
)
pio.templates["cud"] = go.layout.Template(
    layout=go.Layout(
        colorway=CUD_COLORS,
    )
)
pio.templates.default = "plotly_white+cud"
df = pd.read_csv("FOM_Ergebnisse.csv", sep=";", header=0, dtype={'Bereich':'category'})
df["Bereich"] = df["Bereich"].cat.set_categories([
    "Fachkompetenz",
    "Methodenkompetenz",
    "Sozialkompetenz",
    "Persönliche Kompetenz",
    "Diversity-Kompetenz",
    "Ethische Kompetenz",
    "Transferkompetenz"
], ordered=True)
df_grouped = df.groupby(['Bereich']).mean(numeric_only=True).reset_index()
df["Änderung"] = df["Bilanz"] - df["eigene Erwartung"]
fig = px.bar(df_grouped, x="Bereich", y=["eigene Erwartung", "Zwischenbilanz", "Bilanz"], barmode='group')
fig.update_layout(legend={'title_text':''}, yaxis={'title_text':''})
fig.show()
```

## Gewinner

::: {.incremental}
- Ich werde durch mein Studium effektiver nach Informationen suchen können.

- Im Rahmen meines Studiums werde ich meine Fertigkeiten des Computer- und Medieneinsatzes verbessert haben.

- In Folge meines Studiums werde ich meine Arbeit besser organisieren können.
:::

::: {.notes}
1. Methodenkompetenz 1 -> 4 -> 5
2. Methodenkompetenz 1 -> 3 -> 5
3. Methodenkompetenz 2 -> 2 -> 5
:::

## Verlierer

::: {.incremental}
- Durch mein Studium wird es mir besser gelingen, meine Wortbeiträge auf den Punkt zu bringen.

- In Folge meines Studiums werde ich meine Wortbeiträge besser an den Interessen der Zuhörenden ausrichten können.

- Durch mein Studium werde ich öfter auf die Rückmeldung achten, die ich bekommen kann, wenn ich Gelerntes von einer Situation in eine andere übertrage.
:::

::: {.notes}
1. Sozialkompetenz 3 -> 1 -> 1
2. Methodenkompetenz 3 -> 1 -> 1
3. Transferkompetenz 4 -> 1 -> 2
:::
