on:
  workflow_dispatch:
  push:
    branches: [ main ]

name: Quarto Publish

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Install pipenv
        run: pipx install pipenv
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install packages
        run: pipenv requirements > requirements.txt && pip install -r requirements.txt
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}